### ISSUE TITLE
Post a live demo

### ISSUE THREAD

**Issue by specious** [kghandhi/pacman#3]
Making a live demo available would open the door to showcasing this game on [builtwithelm](http://builtwithelm.co/).  That could draw in new contributors.

**Comment by kghandhi** [comment]
@specious Okay Ill work on this over the weekend! Thanks for the suggestion!

**Comment by specious** [comment]
I created a `gh-pages` branch on my fork with a live demo, however I'm [not able to open a corresponding pull request](https://cloud.githubusercontent.com/assets/451178/16368914/f177db9a-3c01-11e6-9dd8-d34d38e27aab.png) presumably because a `gh-pages` branch has to already exist in your repository for me to do that.

I believe you might be able to do this on your side:

```
git checkout --orphan gh-pages
git rm -rf .
git pull git@github.com:specious/pacman.git gh-pages
git push origin gh-pages
```

**Comment by specious** [comment]
Cool, it worked! - https://kghandhi.github.io/pacman/

**Comment by specious** [comment]
I emailed support@github.com about this complication.

**Comment by specious** [comment]
I opened a [pull request](https://github.com/elm-community/builtwithelm/pull/70) at elm-community/builtwithelm.

**Comment by specious** [comment]
As of https://github.com/elm-community/builtwithelm/commit/708a23d0727cbad203c65a8ebcc3a630489e65b4 it is now listed on http://builtwithelm.co ✌️

**Comment by specious** [comment]
@kghandhi, people might click the demo link if you post it in the github repo title:

![kghandhi-pacman-github-header](https://cloud.githubusercontent.com/assets/451178/19055537/6ee08234-8992-11e6-9b23-c7f12d18f62c.png)
